### ISSUE TITLE
Use pre-commit

### ISSUE THREAD

**Issue by zweihuehner** [derekeden/trackio#2]
Add a pre-commit to allow standardized formatting and collaboration.

In a first step I would suggest:

- **pycln**: Deletes imports that are not used.
- **isort**: Sorts imports in a smart manner (e.g. separates external from internal imports).
- **black**: Formats the python code mostly according to pep recommendations.
- **flake8**: Linter tool that checks the code for style and syntax errors.

All of the above pre-commit hooks are uncritical, meaning, they won't fuck up the code when running them.
Later we could also add mypy (enforces type hinting) and pydocstlye (enforces good documentation). But thats a bit more effort as large parts of the code are not yet documented or type hinted (Even though that woul help a lot in debugging and general code understanding).

If you think it is a good idea, I have a .pre-commit-config.yaml file prepared:

```
repos:
  - repo: https://github.com/hadialqattan/pycln
    rev: v2.4.0
    hooks:
      - id: pycln
        args: ["--all"]
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black", --line-length=79]
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        args: [--line-length=79] 
  -   repo: https://github.com/PyCQA/flake8
      rev: 7.0.0
      hooks:
      -   id: flake8
```
